INCLUDE(FindPackageHandleStandardArgs)

IF (NOT CMOCKA_INCLUDE_DIR)
  FIND_PATH(CMOCKA_INCLUDE_DIR cmocka.h HINTS $ENV{CMOCKA_DIR})
ENDIF()

IF (NOT CMOCKA_LIBRARIES)
  FIND_LIBRARY(CMOCKA_LIBRARIES cmocka HINTS $ENV{CMOCKA_DIR})
ENDIF()

MARK_AS_ADVANCED(CMOCKA_INCLUDE_DIR)
MARK_AS_ADVANCED(CMOCKA_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  CMOCKA
  DEFAULT_MSG
  CMOCKA_LIBRARIES
  CMOCKA_INCLUDE_DIR
)

